name: giderivar
description: "GideriVar - Global Sustainable Marketplace"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  http: ^1.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  # Firebase (güncel uyumlu versiyon seti)
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0  
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  flutter_local_notifications: ^19.4.0
  # Google Sign-In (latest 7.x version)
  google_sign_in: ^7.1.1
  # Image handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  # Location services  
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  # AdMob for rewarded ads
  google_mobile_ads: ^6.0.0
  # URL launcher for contact methods
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 23 # Firebase Auth requires minimum SDK 23
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"  

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    # - assets/lottie/people-moving-boxes.json
    # - assets/lottie/loading-workers.json
