// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeHkKGxpHc3o7n-eODS8mqSGpdh6LQ_Ak',
    appId: '1:146943865377:web:375bf13e4856c74df1e960',
    messagingSenderId: '146943865377',
    projectId: 'giderivarapp',
    authDomain: 'giderivarapp.firebaseapp.com',
    storageBucket: 'giderivarapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEnZt7c7-wjtSI1FkClhJaFkINAwxA2DM',
    appId: '1:146943865377:android:2724a5b88fa1c49bf1e960',
    messagingSenderId: '146943865377',
    projectId: 'giderivarapp',
    storageBucket: 'giderivarapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAksnLymiFjF527t8foYJ0OAApZD_olHqs',
    appId: '1:146943865377:ios:828f99dd3e7bcf99f1e960',
    messagingSenderId: '146943865377',
    projectId: 'giderivarapp',
    storageBucket: 'giderivarapp.firebasestorage.app',
    iosBundleId: 'com.moat.giderivar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAksnLymiFjF527t8foYJ0OAApZD_olHqs',
    appId: '1:146943865377:ios:828f99dd3e7bcf99f1e960',
    messagingSenderId: '146943865377',
    projectId: 'giderivarapp',
    storageBucket: 'giderivarapp.firebasestorage.app',
    iosBundleId: 'com.moat.giderivar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeHkKGxpHc3o7n-eODS8mqSGpdh6LQ_Ak',
    appId: '1:146943865377:web:375bf13e4856c74df1e960',
    messagingSenderId: '146943865377',
    projectId: 'giderivarapp',
    authDomain: 'giderivarapp.firebaseapp.com',
    storageBucket: 'giderivarapp.firebasestorage.app',
  );
}
